### ISSUE TITLE
Doesn't seem to execute anything

### ISSUE THREAD

**Issue by asanger** [viewone/wp-cli-environment#1]
Hi - I saw your issue over on the wp-cli repo from last year, which lead me here. This seems to be -**exactly** what I'm looking for, however I don't believe that it's working (environment names are valid commands, but nothing happens). I will try to debug it myself, but I wanted to see if you have had it working recently, or if you've found a different way to handle multiple wp-cli.yml files for different environments.

**Comment by kierzniak** [comment]
Hi,
as you see wp-cli-environment was not been updated recently. I assume that it is incompatible with new version of wp-cli. It was working with 0.15.1.

**Comment by asanger** [comment]
hey, thanks for the response. I'll play around with it a bit and see if I can get it working. Thanks for the work that you put into this.
